/* nanopb descriptor for BoardConfig — auto-generated by generate_nanopb.py */
#ifndef BOARD_CONFIG_PB_H
#define BOARD_CONFIG_PB_H

#include <pb.h>
#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    int32_t  uart_1_protocol;  /* enum iFOC.DataType.Comm.UARTProtocol */
    int32_t  uart_1_baudrate;  /* enum iFOC.DataType.Comm.UARTBaudrate */
    uint32_t pwm_wave_freq;
    uint32_t speed_loop_freq;
    float    bus_overvoltage_limit;
    float    bus_undervoltage_limit;
    float    bus_max_positive_current;
    float    bus_max_negative_current;
    float    bus_sense_shunt_ohm;
    float    max_regen_current;
    float    current_sense_gain;
    float    current_sense_shunt_ohm;
    uint32_t current_sense_f_lp;
    bool     play_startup_tone;
    bool     use_square_wave_tone;
    bool     enable_can_terminal_resistor;
} BoardConfig_data;

#define BoardConfig_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, INT32, uart_1_protocol,                1) \
X(a, STATIC, SINGULAR, INT32, uart_1_baudrate,                2) \
X(a, STATIC, SINGULAR, UINT32, pwm_wave_freq,                  5) \
X(a, STATIC, SINGULAR, UINT32, speed_loop_freq,                6) \
X(a, STATIC, SINGULAR, FLOAT, bus_overvoltage_limit,         11) \
X(a, STATIC, SINGULAR, FLOAT, bus_undervoltage_limit,        12) \
X(a, STATIC, SINGULAR, FLOAT, bus_max_positive_current,      13) \
X(a, STATIC, SINGULAR, FLOAT, bus_max_negative_current,      14) \
X(a, STATIC, SINGULAR, FLOAT, bus_sense_shunt_ohm,           15) \
X(a, STATIC, SINGULAR, FLOAT, max_regen_current,             19) \
X(a, STATIC, SINGULAR, FLOAT, current_sense_gain,            21) \
X(a, STATIC, SINGULAR, FLOAT, current_sense_shunt_ohm,       22) \
X(a, STATIC, SINGULAR, UINT32, current_sense_f_lp,            24) \
X(a, STATIC, SINGULAR, BOOL, play_startup_tone,             31) \
X(a, STATIC, SINGULAR, BOOL, use_square_wave_tone,          32) \
X(a, STATIC, SINGULAR, BOOL, enable_can_terminal_resistor,  33)

#define BoardConfig_CALLBACK NULL
#define BoardConfig_DEFAULT  NULL

extern const pb_msgdesc_t BoardConfig_data_msg;
#define BoardConfig_data_fields (&BoardConfig_data_msg)

#ifdef __cplusplus
}
#endif

#endif /* BOARD_CONFIG_PB_H */
