/* auto-generated by generate_nanopb.py — source: Comm/uart_protocol.proto */
#ifndef COMM_UART_PROTOCOL_H
#define COMM_UART_PROTOCOL_H

#include <cstdint>
// Include external proto definitions

namespace iFOC {
namespace DataType {
namespace Comm {

enum class UARTProtocol : uint32_t
{
  UNIFIED = 0,
  VOFA = 1,
  RAW_PROTO = 2,
  MATLAB = 3,
  ASCII = 4
};

} // End of namespace Comm
} // End of namespace DataType
} // End of namespace iFOC
#endif // COMM_UART_PROTOCOL_H
