/* nanopb descriptor for DCMotorConfig — auto-generated by generate_nanopb.py */
#ifndef DC_MOTOR_CONFIG_PB_H
#define DC_MOTOR_CONFIG_PB_H

#include <pb.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    uint32_t node_id;
    float    max_voltage;
    float    max_current;
    float    deduction_ratio;
    float    max_output_speed_rpm;
    float    pos_kp;
    float    vel_kp;
    float    vel_ki;
    float    watchdog_timeout_sec;
} DCMotorConfig_data;

#define DCMotorConfig_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT32, node_id,                1) \
X(a, STATIC, SINGULAR, FLOAT, max_voltage,            9) \
X(a, STATIC, SINGULAR, FLOAT, max_current,           10) \
X(a, STATIC, SINGULAR, FLOAT, deduction_ratio,       29) \
X(a, STATIC, SINGULAR, FLOAT, max_output_speed_rpm,  30) \
X(a, STATIC, SINGULAR, FLOAT, pos_kp,                31) \
X(a, STATIC, SINGULAR, FLOAT, vel_kp,                32) \
X(a, STATIC, SINGULAR, FLOAT, vel_ki,                33) \
X(a, STATIC, SINGULAR, FLOAT, watchdog_timeout_sec,  34)

#define DCMotorConfig_CALLBACK NULL
#define DCMotorConfig_DEFAULT  NULL

extern const pb_msgdesc_t DCMotorConfig_data_msg;
#define DCMotorConfig_data_fields (&DCMotorConfig_data_msg)

#ifdef __cplusplus
}
#endif

#endif /* DC_MOTOR_CONFIG_PB_H */
