/* nanopb descriptor for FOCMotorConfig — auto-generated by generate_nanopb.py */
#ifndef FOC_MOTOR_CONFIG_PB_H
#define FOC_MOTOR_CONFIG_PB_H

#include <pb.h>
#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    uint32_t node_id;
    float    current_loop_bandwidth;
    char     node_name[33];  /* max 32 chars + null, STRING field */
    float    calibration_voltage;
    float    calibration_current;
    float    max_voltage;
    float    max_current;
    float    phase_resistance;
    bool     phase_resistance_valid;
    float    phase_inductance;
    float    q_axis_inductance;
    float    d_axis_inductance;
    bool     phase_inductance_valid;
    bool     sensor_direction_clockwise;
    bool     sensor_direction_valid;
    uint32_t pole_pairs;
    bool     pole_pairs_valid;
    float    sensor_zero_offset_rad;
    bool     sensor_zero_offset_valid;
    float    kv_rating;
    bool     kv_rating_valid;
    float    torque_constant;
    bool     torque_constant_valid;
    float    flux_linkage;
    bool     flux_linkage_valid;
    float    deduction_ratio;
    float    max_output_speed_rpm;
    float    pos_kp;
    float    vel_kp;
    float    vel_ki;
    float    watchdog_timeout_sec;
    float    sensor_speed_f_lp;
    bool     startup_sequence_enabled;
    bool     startup_basic_param_calibration;
    bool     startup_encoder_index_search;
    bool     startup_encoder_calibration;
    bool     startup_extend_param_calibration;
    bool     startup_sensored_closed_loop;
    bool     startup_sensorless_closed_loop;
    uint32_t can_heartbeat_interval_ms;
    uint32_t can_feedback_interval_ms;
    uint32_t can_misc_fdbk_interval_ms;
    bool     enable_harmonic_suppression;
    bool     enable_anticogging;
    float    anticogging_base_pos_err_deg;
    float    anticogging_base_vel_err_rpm;
    float    traj_output_speed_limit_rpm;
    float    traj_output_accel_limit_rpm;
    float    traj_output_decel_limit_rpm;
    float    mit_output_pos_range_deg;
    float    mit_output_vel_range_rpm;
    float    mit_output_tor_range_nm;
} FOCMotorConfig_data;

#define FOCMotorConfig_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT32, node_id,                            1) \
X(a, STATIC, SINGULAR, FLOAT, current_loop_bandwidth,             2) \
X(a, STATIC, SINGULAR, STRING, node_name,                          3) \
X(a, STATIC, SINGULAR, FLOAT, calibration_voltage,                7) \
X(a, STATIC, SINGULAR, FLOAT, calibration_current,                8) \
X(a, STATIC, SINGULAR, FLOAT, max_voltage,                        9) \
X(a, STATIC, SINGULAR, FLOAT, max_current,                       10) \
X(a, STATIC, SINGULAR, FLOAT, phase_resistance,                  11) \
X(a, STATIC, SINGULAR, BOOL, phase_resistance_valid,            12) \
X(a, STATIC, SINGULAR, FLOAT, phase_inductance,                  13) \
X(a, STATIC, SINGULAR, FLOAT, q_axis_inductance,                 14) \
X(a, STATIC, SINGULAR, FLOAT, d_axis_inductance,                 15) \
X(a, STATIC, SINGULAR, BOOL, phase_inductance_valid,            16) \
X(a, STATIC, SINGULAR, BOOL, sensor_direction_clockwise,        17) \
X(a, STATIC, SINGULAR, BOOL, sensor_direction_valid,            18) \
X(a, STATIC, SINGULAR, UINT32, pole_pairs,                        19) \
X(a, STATIC, SINGULAR, BOOL, pole_pairs_valid,                  20) \
X(a, STATIC, SINGULAR, FLOAT, sensor_zero_offset_rad,            21) \
X(a, STATIC, SINGULAR, BOOL, sensor_zero_offset_valid,          22) \
X(a, STATIC, SINGULAR, FLOAT, kv_rating,                         23) \
X(a, STATIC, SINGULAR, BOOL, kv_rating_valid,                   24) \
X(a, STATIC, SINGULAR, FLOAT, torque_constant,                   25) \
X(a, STATIC, SINGULAR, BOOL, torque_constant_valid,             26) \
X(a, STATIC, SINGULAR, FLOAT, flux_linkage,                      27) \
X(a, STATIC, SINGULAR, BOOL, flux_linkage_valid,                28) \
X(a, STATIC, SINGULAR, FLOAT, deduction_ratio,                   29) \
X(a, STATIC, SINGULAR, FLOAT, max_output_speed_rpm,              30) \
X(a, STATIC, SINGULAR, FLOAT, pos_kp,                            31) \
X(a, STATIC, SINGULAR, FLOAT, vel_kp,                            32) \
X(a, STATIC, SINGULAR, FLOAT, vel_ki,                            33) \
X(a, STATIC, SINGULAR, FLOAT, watchdog_timeout_sec,              34) \
X(a, STATIC, SINGULAR, FLOAT, sensor_speed_f_lp,                 35) \
X(a, STATIC, SINGULAR, BOOL, startup_sequence_enabled,          37) \
X(a, STATIC, SINGULAR, BOOL, startup_basic_param_calibration,   38) \
X(a, STATIC, SINGULAR, BOOL, startup_encoder_index_search,      39) \
X(a, STATIC, SINGULAR, BOOL, startup_encoder_calibration,       40) \
X(a, STATIC, SINGULAR, BOOL, startup_extend_param_calibration,  41) \
X(a, STATIC, SINGULAR, BOOL, startup_sensored_closed_loop,      42) \
X(a, STATIC, SINGULAR, BOOL, startup_sensorless_closed_loop,    43) \
X(a, STATIC, SINGULAR, UINT32, can_heartbeat_interval_ms,         54) \
X(a, STATIC, SINGULAR, UINT32, can_feedback_interval_ms,          55) \
X(a, STATIC, SINGULAR, UINT32, can_misc_fdbk_interval_ms,         56) \
X(a, STATIC, SINGULAR, BOOL, enable_harmonic_suppression,       60) \
X(a, STATIC, SINGULAR, BOOL, enable_anticogging,                61) \
X(a, STATIC, SINGULAR, FLOAT, anticogging_base_pos_err_deg,      62) \
X(a, STATIC, SINGULAR, FLOAT, anticogging_base_vel_err_rpm,      63) \
X(a, STATIC, SINGULAR, FLOAT, traj_output_speed_limit_rpm,       70) \
X(a, STATIC, SINGULAR, FLOAT, traj_output_accel_limit_rpm,       71) \
X(a, STATIC, SINGULAR, FLOAT, traj_output_decel_limit_rpm,       72) \
X(a, STATIC, SINGULAR, FLOAT, mit_output_pos_range_deg,          73) \
X(a, STATIC, SINGULAR, FLOAT, mit_output_vel_range_rpm,          74) \
X(a, STATIC, SINGULAR, FLOAT, mit_output_tor_range_nm,           75)

#define FOCMotorConfig_CALLBACK NULL
#define FOCMotorConfig_DEFAULT  NULL

extern const pb_msgdesc_t FOCMotorConfig_data_msg;
#define FOCMotorConfig_data_fields (&FOCMotorConfig_data_msg)

#ifdef __cplusplus
}
#endif

#endif /* FOC_MOTOR_CONFIG_PB_H */
